<?php require_once dirname(__DIR__).'/app/bootstrap.php'; ?>
<!doctype html><html lang="tr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><title>Ödediğiniz Bedel — Dumansız Hayat</title><link rel="icon" href="assets/favicon.svg"><link rel="stylesheet" href="assets/experience.css?v=1"><link rel="stylesheet" href="assets/impact.css?v=2"><script src="assets/impact-math.js" defer></script><script src="assets/impact.js?v=3" defer></script><link rel="stylesheet" href="assets/relief.css?v=1"><link rel="stylesheet" href="assets/readability.css?v=1"><link rel="stylesheet" href="assets/palette.css?v=1"><link rel="stylesheet" href="assets/health-risks.css?v=1"><?php require_once dirname(__DIR__).'/app/pwa.php';pwa_head(); ?></head><body class="relief-surface app-screen"><header class="app-header"><a class="brand" href="/">≈ dumansız<span>hayat</span></a><nav><a href="rehber.php">Keşfet</a><a class="active" href="etkiler.php">Ödediğiniz Bedel</a><a href="poliklinikler.php">Sigara Bırakma Poliklinikleri</a></nav></header>
<main class="impact-screen"><section class="impact-controls"><p class="eyebrow">DUMAN GİDER. BEDELİ KALIR.</p><h1>Hayatından <br><em>neler gidiyor?</em></h1><div class="impact-tabs" role="tablist" aria-label="Etki türü"><button type="button" role="tab" id="tab-money" aria-controls="impact-panel" data-impact="money" aria-selected="true">Para</button><button type="button" role="tab" id="tab-health" aria-controls="impact-panel" data-impact="health" aria-selected="false" tabindex="-1">Sağlık</button><button type="button" role="tab" id="tab-time" aria-controls="impact-panel" data-impact="time" aria-selected="false" tabindex="-1">Zaman</button></div>
<div class="sliders"><label for="packs">Günde kaç paket? <output id="packs-label">1 paket</output></label><input type="range" id="packs" min="0" max="3" step="0.1" value="1"><label for="years">Kaç yıldır? <output id="years-label">5 yıl</output></label><input type="range" id="years" min="0" max="40" step="1" value="5"><div class="price-row"><label for="pack-price">Paket fiyatı <span>₺</span></label><input type="number" id="pack-price" min="0" max="1000" step="1" value="100" inputmode="decimal"></div></div><button class="calculation-info" id="assumptions-open" type="button">Hesaplama ve kaynaklar ↗</button><a class="impact-support" href="rehber.php">Bundan sonraki adımın senin. <span>↗</span></a></section>
<section class="impact-stage" id="impact-panel" role="tabpanel" aria-labelledby="tab-money"><div class="impact-total"><span id="metric-label">SİGARAYA AYRILAN PARA</span><output id="metric-value" aria-live="polite">182.500 ₺</output><p id="metric-caption">Bugünkü paket fiyatıyla tahmini toplam.</p></div>
<div class="visual-stage"><div id="money-visual" class="effect-visual"><svg id="money-svg" viewBox="0 0 660 340" role="img" aria-label="Sigara harcaması arttıkça dolan para çuvalları"><defs><linearGradient id="bag-body" x1="0" y1="0" x2="1" y2="1"><stop stop-color="#d8b783"/><stop offset=".45" stop-color="#af8959"/><stop offset="1" stop-color="#755635"/></linearGradient><linearGradient id="bag-money" x1="0" y1="0" x2="0" y2="1"><stop stop-color="#ffe1a1"/><stop offset="1" stop-color="#bd8346"/></linearGradient><filter id="bag-shadow" x="-30%" y="-20%" width="170%" height="160%"><feDropShadow dx="5" dy="8" stdDeviation="4" flood-color="#031b15" flood-opacity=".5"/></filter></defs><g id="bags"></g></svg><span id="bag-overflow"></span></div>
<div id="health-visual" class="effect-visual" hidden>
<div class="risk-picker" role="tablist" aria-label="Sağlık riskleri"><button type="button" role="tab" id="risk-tab-heart" data-risk="heart" aria-controls="risk-heart" aria-selected="true">Kalp krizi</button><button type="button" role="tab" id="risk-tab-copd" data-risk="copd" aria-controls="risk-copd" aria-selected="false" tabindex="-1">KOAH</button><button type="button" role="tab" id="risk-tab-cancer" data-risk="cancer" aria-controls="risk-cancer" aria-selected="false" tabindex="-1">Akciğer kanseri</button></div>
<article class="risk-card" id="risk-heart" role="tabpanel" aria-labelledby="risk-tab-heart" tabindex="0">
<span class="risk-kicker">01 / KALP KRİZİ RİSKİ</span><h2>“Beni rahatlatıyor.”<br><em>Peki ya kalbini?</em></h2>
<div class="risk-number">2,2–3,5 <span>kat</span></div><p class="risk-comparison">Sigara içenlerde, hiç içmemiş olanlara kıyasla.</p>
<p class="risk-context">UK Biobank araştırmasında kalp krizi için: erkeklerde 2,23; kadınlarda 3,46 kat.</p>
<div class="risk-turn"><span>YÖNÜ DEĞİŞTİREBİLİRSİN</span><p>Bıraktıktan 1–2 yıl sonra kalp krizi riski belirgin biçimde düşer.</p></div>
<a class="risk-source" href="https://www.bmj.com/content/363/bmj.k4247" target="_blank" rel="noopener">Araştırmayı gör · BMJ, 2018 ↗</a></article>
<article class="risk-card" id="risk-copd" role="tabpanel" aria-labelledby="risk-tab-copd" tabindex="0" hidden>
<span class="risk-kicker">02 / KOAH GELİŞME RİSKİ</span><h2>Bir sigara birkaç dakika.<br><em>Nefesin bir ömür.</em></h2>
<div class="risk-number"><small>yaklaşık</small>4 <span>kat</span></div><p class="risk-comparison">Sigara içenlerde, içmeyenlere kıyasla.</p>
<p class="risk-context">22 çalışmanın birleştirildiği analizde KOAH gelişme riski 4,01 kat bulundu.</p>
<div class="risk-turn"><span>NEFESİN İÇİN BUGÜN</span><p>Bırakmak KOAH gelişme riskini azaltır; KOAH varsa ilerlemesini yavaşlatır.</p></div>
<a class="risk-source" href="https://doi.org/10.1016/j.chest.2016.03.060" target="_blank" rel="noopener">Araştırmayı gör · CHEST, 2016 ↗</a></article>
<article class="risk-card" id="risk-cancer" role="tabpanel" aria-labelledby="risk-tab-cancer" tabindex="0" hidden>
<span class="risk-kicker">03 / AKCİĞER KANSERİ RİSKİ</span><h2>Duman dağılır.<br><em>Risk kalır.</em></h2>
<div class="risk-number"><small>yaklaşık</small>25 <span>kat</span></div><p class="risk-comparison">Sigara içenlerde, içmeyenlere kıyasla.</p>
<p class="risk-context">CDC’nin özetlediği verilere göre akciğer kanseri gelişme riski.</p>
<div class="risk-turn"><span>SONRAKİ SAYFAYI SEN YAZ</span><p>Bıraktıktan 10–15 yıl sonra akciğer kanseri için ek risk yaklaşık yarıya iner.</p></div>
<a class="risk-source" href="https://www.cdc.gov/tobacco/about/cigarettes-and-cancer.html" target="_blank" rel="noopener">Kaynağı gör · CDC ↗</a></article>
<p class="risk-footnote">Toplum verileridir; kişisel risk yüzdesi değildir. <button type="button" id="risk-details">Rakamlar ne demek? ↗</button></p>
</div>
<div id="time-visual" class="effect-visual" hidden><div class="time-dial"><svg viewBox="0 0 240 240" aria-hidden="true"><circle class="clock-track" cx="120" cy="120" r="96"/><circle id="clock-progress" cx="120" cy="120" r="96"/><path class="clock-hands" d="M120 56V120L160 144"/><circle cx="120" cy="120" r="6" fill="#f0bd78"/></svg><span id="time-days">127 gün</span></div></div></div>
<div class="visual-bottom"><p id="visual-caption">Her çuval 25.000 ₺. Doluluk kalan tutarı gösterir.</p><span class="live-pill"><i></i> SEÇİMİNLE DEĞİŞİR</span></div></section></main>
<footer class="app-footer"><a href="/">← Ana sayfa</a><a href="tel:171">Destek al · ALO 171 ↗</a><span>Verilerin kaydedilmez</span></footer>
<dialog id="assumptions-dialog" aria-labelledby="assumptions-title"><h2 id="assumptions-title">Hesabın arkasında ne var?</h2><p>Bir paket 20 sigara, bir yıl 365 gün kabul edilir. Para hesabı seçtiğin sabit paket fiyatını tüm döneme uygular; geçmişte gerçekten ödediğin tutar değildir. Her çuval 25.000 ₺’yi temsil eder. Ekranda en fazla 18 çuval çizilir; fazlası ayrıca belirtilir.</p><p>Zaman hesabı sigara başına seçtiğin dakika üzerinden yapılır. Bu, sigara içmeye ayrılan süredir; yaşam süresinden kaybedilen gün hesabı değildir.</p><label for="minutes">Sigara başına dakika <input id="minutes" type="number" min="1" max="15" step="1" value="5"></label><h3>Sağlık rakamları neyi anlatıyor?</h3><p>Bunlar sigara içen ve içmeyen grupları karşılaştıran araştırma sonuçlarıdır. “4 kat”, hastalanma olasılığının %400 olduğu anlamına gelmez. Yaş, cinsiyet, kullanım miktarı, süre ve diğer etkenlere göre kişisel risk değişir. Burada kişisel risk hesaplanmaz; paket/yıl ayarları bu istatistikleri değiştirmez.</p>
<p><strong>Kalp krizi:</strong> UK Biobank kohortunda, başlangıçta kalp-damar hastalığı olmayan 40–69 yaşındaki katılımcılarda, halen sigara içenler hiç içmemiş olanlarla karşılaştırıldı. Düzeltilmiş hazard oranı erkeklerde 2,23 (%95 güven aralığı 2,03–2,44), kadınlarda 3,46 (3,02–3,98). Karttaki 2,2–3,5 aralığı bu iki tahminin yuvarlanmış gösterimidir; güven aralığı değildir. <a href="https://www.bmj.com/content/363/bmj.k4247" target="_blank" rel="noopener">BMJ · 2018</a></p>
<p><strong>KOAH:</strong> SmokeHaz derlemesinde 22 çalışmanın birleşik göreli risk tahmini 4,01 (%95 güven aralığı 3,18–5,05). Çalışma sonuçları arasında önemli farklılıklar vardır; herkes için sabit bir çarpan değildir. <a href="https://doi.org/10.1016/j.chest.2016.03.060" target="_blank" rel="noopener">CHEST · 2016</a></p>
<p><strong>Akciğer kanseri:</strong> CDC, sigara içenlerde gelişme riskini içmeyenlere göre yaklaşık 25 kat olarak özetler. Bu bir ölüm riski ya da kişisel olasılık hesabı değildir. <a href="https://www.cdc.gov/tobacco/about/cigarettes-and-cancer.html" target="_blank" rel="noopener">CDC · Sigara ve kanser</a></p>
<p><strong>Bırakmanın kazancı:</strong> Süreler sigara içmeye devam etmeyle karşılaştırılan genel verilerdir. Akciğer kanserindeki “ek risk”, temel riskin üzerindeki kısmı anlatır. Bırakmak her yaşta yarar sağlar. <a href="https://www.cdc.gov/tobacco/about/benefits-of-quitting.html" target="_blank" rel="noopener">CDC · Bırakmanın faydaları</a></p><button type="button" id="assumptions-close">Ekrana dön</button></dialog><?php pwa_controls('cost'); ?></body></html>
