<?php
require_once dirname(__DIR__).'/app/bootstrap.php';
$clinics = require dirname(__DIR__).'/app/clinics.php';
$districts = ['Büyükorhan','Gemlik','Gürsu','İnegöl','Mudanya','Mustafakemalpaşa','Nilüfer','Orhangazi','Osmangazi','Yenişehir','Yıldırım'];
?>
<!doctype html>
<html lang="tr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Bursa Sigara Bırakma Poliklinikleri — Dumansız Yaşam</title><meta name="description" content="Bursa sigara bırakma poliklinikleri: kurum adresleri, telefonlar ve Google Haritalar yol tarifleri. İlçene göre profesyonel destek bul."><link rel="icon" href="assets/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="assets/clinics.css"><script src="assets/clinics.js" defer></script></head>
<body><a class="skip" href="#merkezler">Merkezlere geç</a>
<header class="site-header"><a class="brand" href="/" aria-label="Dumansız Yaşam ana sayfa"><span aria-hidden="true">≈</span> dumansız<b>yaşam</b></a><nav aria-label="Ana menü"><a href="rehber.php">Özgürlüğünü keşfet ↗</a><a class="active" href="poliklinikler.php" aria-current="page">Bursa’da destek</a></nav></header>
<main>
<section class="intro"><div class="intro-copy"><p class="eyebrow"><span></span> BURSA · BİRLİKTE DAHA KOLAY</p><h1>İlk adımın için<br><em>yakınında biri var.</em></h1><p class="lead">Bursa sigara bırakma poliklinikleri.<br>İlçeni seç, merkezini bul, yeni başlangıcına ulaş.</p><a class="jump" href="#merkezler">Destek noktalarını keşfet <span aria-hidden="true">↓</span></a></div><aside class="support"><span class="support-label">BİR KONUŞMAYLA BAŞLA</span><a href="tel:171" aria-label="ALO 171 sigara bırakma danışma hattını ara">ALO <strong>171</strong><span aria-hidden="true">↗</span></a><p>Nereden başlayacağını bilmiyorsan,<br>sigara bırakma danışma hattı yanında.</p><div><a href="https://mhrs.gov.tr/" target="_blank" rel="noopener">MHRS’den randevu ↗</a><a href="tel:182">ALO 182’yi ara ↗</a></div></aside></section>
<section class="directory" id="merkezler" aria-labelledby="directory-title"><div class="directory-title"><div><p class="eyebrow">SANA UYGUN NOKTAYI BUL</p><h2 id="directory-title">Bursa’da destek.</h2></div><p><?=count($clinics)?> merkez <span> / </span> <?=count($districts)?> ilçe</p></div>
<form class="filters" role="search" aria-label="Poliklinik ara" hidden><label class="search-label" for="clinic-search">Kurum veya adres ara<input id="clinic-search" type="search" placeholder="Örn. Nilüfer, Şehir Hastanesi…" autocomplete="off"></label><label for="district">İlçe<select id="district"><option value="">Tüm ilçeler</option><?php foreach($districts as $district): ?><option value="<?=e($district)?>"><?=e($district)?></option><?php endforeach; ?></select></label><button type="reset">Temizle ↺</button></form>
<div class="results-bar"><p id="result-count" role="status" aria-live="polite"><?=count($clinics)?> merkez gösteriliyor</p><a href="#kaynaklar">Kaynaklar ve güncellik ↗</a></div>
<div class="clinic-grid">
<?php foreach($clinics as $i=>$clinic): $query=$clinic['name'].' '.$clinic['address']; $map='https://www.google.com/maps/search/?api=1&query='.rawurlencode($query); $directions='https://www.google.com/maps/dir/?api=1&destination='.rawurlencode($query); ?>
<article class="clinic-card" data-district="<?=e($clinic['district'])?>" data-search="<?=e($query.' '.$clinic['type'])?>"><div class="card-top"><span class="district-tag"><?=e($clinic['district'])?></span><span class="card-number"><?=str_pad((string)($i+1),2,'0',STR_PAD_LEFT)?></span></div><p class="clinic-type"><?=e($clinic['type'])?></p><h3><?=e($clinic['name'])?></h3><div class="address"><span aria-hidden="true">⌖</span><address><?=e($clinic['address'])?></address></div><div class="phones"><span class="field-label">TELEFON<?=isset($clinic['extension'])?' · DAHİLİ '.e($clinic['extension']):''?></span><?php foreach($clinic['phones'] as $phone): ?><a href="tel:+9<?=preg_replace('/\D/','',$phone)?>"><?=e($phone)?> <span aria-hidden="true">↗</span></a><?php endforeach; ?></div>
<?php if(isset($clinic['note'])): ?><details class="clinic-note"><summary>Başvuru ve adres notu</summary><p><?=e($clinic['note'])?></p><?php if(isset($clinic['alternate_phone'])): ?><a href="tel:+9<?=preg_replace('/\D/','',$clinic['alternate_phone'])?>">Alternatif numarayı ara ↗</a><?php endif; ?></details><?php endif; ?>
<div class="card-actions"><a class="map-link" href="<?=e($map)?>" target="_blank" rel="noopener" aria-label="<?=e($clinic['name'])?> Google Haritalar’da aç">Google Haritalar <span aria-hidden="true">↗</span></a><a class="directions" href="<?=e($directions)?>" target="_blank" rel="noopener" aria-label="<?=e($clinic['name'])?> için yol tarifi al">Yol tarifi ↗</a></div><div class="card-sources"><a href="<?=e($clinic['source'])?>" target="_blank" rel="noopener">Poliklinik kaynağı ↗</a><?php if(isset($clinic['contact_source'])): ?><a href="<?=e($clinic['contact_source'])?>" target="_blank" rel="noopener">Kurum bilgileri ↗</a><?php endif; ?></div></article>
<?php endforeach; ?>
</div><div class="empty" id="no-results" hidden><h3>Bu aramayla bir merkez bulunamadı.</h3><p>Farklı bir kurum adı deneyebilir veya ilçe seçimini kaldırabilirsin.</p><button type="button" id="show-all">Tüm merkezleri göster</button></div>
</section>
<section class="source-note" id="kaynaklar"><div><p class="eyebrow">YOLA ÇIKMADAN ÖNCE</p><h2>Bir aramayla<br>teyit et.</h2></div><div><p>Çalışma günleri, hekim ve hizmet binası değişebilir. Gitmeden önce kurumu arayıp sigara bırakma polikliniğinin adresini ve randevu koşullarını doğrula. Telefonlar poliklinik, merkez veya hastane santral numarası olabilir.</p><p>Bu rehber, <a href="https://alo171.saglik.gov.tr/TR-68192/bursa.html" target="_blank" rel="noopener">ALO 171’in Bursa listesindeki 15 kaydın tamamını</a> ve <a href="https://bursasehir.saglik.gov.tr/TR-661722/poliklinik-hakkinda.html" target="_blank" rel="noopener">Bursa Şehir Hastanesinin polikliniğini</a> içerir. İletişim bilgileri Bakanlık ve kurum sayfalarıyla karşılaştırılmıştır; kaynaklar her kartta yer alır. Şehirdeki yeni açılan veya henüz bu kaynaklarda yayımlanmayan tüm birimleri kapsadığı garanti edilemez.</p><p class="checked">Son kaynak kontrolü: <time datetime="2026-10-03">3 Ekim 2026</time> · Telefonla doğrulama yapılmamıştır.</p><p>İlçeni bulamadıysan güncel yönlendirme için <a href="tel:171">ALO 171’i ara ↗</a></p></div></section>
</main><footer><a class="brand" href="/">≈ dumansız<b>yaşam</b></a><p>Daha hafif. Daha özgür. Daha sen.</p><a href="/">Ana sayfaya dön ↗</a></footer>
</body></html>
