<?php
declare(strict_types=1);
// Public institutional contacts checked on 2026-10-03. Keep service and contact sources separate.
$alo171 = 'https://alo171.saglik.gov.tr/TR-68192/bursa.html';
$shmContacts = 'https://alo191.saglik.gov.tr/TR-89210/bursa.html';
return [
    ['name'=>'Bursa Şehir Hastanesi', 'district'=>'Nilüfer', 'type'=>'Hastane', 'address'=>'Doğanköy Mah. Şifa Cad. No:1, 16250 Nilüfer / Bursa', 'phones'=>['0224 975 00 00'], 'source'=>'https://bursasehir.saglik.gov.tr/TR-661722/poliklinik-hakkinda.html', 'contact_source'=>'https://bursasehir.saglik.gov.tr/TR-421894/iletisim-bilgileri.html', 'note'=>'Hastane santralinden sigara bırakma polikliniğine yönlendirme isteyin.'],
    ['name'=>'Bursa Uludağ Üniversitesi Tıp Fakültesi Hastanesi', 'district'=>'Nilüfer', 'type'=>'Üniversite hastanesi', 'address'=>'Görükle Kampüsü, Temel Bilimler Binası, Aile Hekimliği ABD, 3. kat (Rektörlük binası yanı), Nilüfer / Bursa', 'phones'=>['0224 295 00 00'], 'source'=>$alo171, 'note'=>'Aile Hekimliği birimi için hastane santralini arayın.'],
    ['name'=>'Nilüfer Sağlıklı Hayat Merkezi', 'district'=>'Nilüfer', 'type'=>'Sağlıklı Hayat Merkezi', 'address'=>'Fethiye Mah. Nilüfer Hatun Cad. Duyum Sok. No:1/A, Nilüfer / Bursa', 'phones'=>['0224 441 74 79','0224 443 45 61','0224 453 17 80'], 'source'=>$alo171, 'contact_source'=>$shmContacts, 'note'=>'Bakanlık iletişim kaydındaki adres kullanıldı. ALO 171 listesinde kapı numarası 13/A olarak geçiyor; giriş bilgisini telefonla teyit edin.'],
    ['name'=>'Çekirge Devlet Hastanesi', 'district'=>'Osmangazi', 'type'=>'Hastane', 'address'=>'Hüdavendigar Mah. 2. Nazlı Cad. No:1/A, Osmangazi / Bursa', 'phones'=>['0224 239 36 36'], 'source'=>$alo171, 'contact_source'=>'https://cekirgedh.saglik.gov.tr/TR-1499398/sigara-biraktirma-poliklinigi.html', 'note'=>'Adres, ALO 171 poliklinik kaydıdır. Başvuru binasını santralden doğrulayın.'],
    ['name'=>'Osmangazi 1 No’lu Sağlıklı Hayat Merkezi', 'district'=>'Osmangazi', 'type'=>'Sağlıklı Hayat Merkezi', 'address'=>'Hüdavendigar Mah. Mete Cad. No:1, Osmangazi / Bursa', 'phones'=>['0224 232 25 44'], 'source'=>$alo171, 'contact_source'=>'https://bursaism.saglik.gov.tr/TR-15567/osmangazi-ilce-saglik-mudurlugu.html', 'note'=>'Adres, İl Sağlık Müdürlüğünün güncel birim iletişim sayfasından alınmıştır.'],
    ['name'=>'Bursa Yüksek İhtisas Eğitim ve Araştırma Hastanesi', 'district'=>'Yıldırım', 'type'=>'Hastane', 'address'=>'Mimar Sinan Mah. Emniyet Cad., Yıldırım / Bursa', 'phones'=>['0224 295 50 00'], 'source'=>$alo171, 'note'=>'Göğüs Hastalıkları birimi için santralden yönlendirme isteyin.'],
    ['name'=>'Yıldırım 1 No’lu Sağlıklı Hayat Merkezi', 'district'=>'Yıldırım', 'type'=>'Sağlıklı Hayat Merkezi', 'address'=>'152 Evler Mah. Ankara Yolu Cad. 1. Ertuğrul Sok., Yıldırım / Bursa', 'phones'=>['0224 502 80 78'], 'source'=>$alo171],
    ['name'=>'Gemlik Devlet Hastanesi', 'district'=>'Gemlik', 'type'=>'Hastane', 'address'=>'Cihatlı Mah. Cihatlı Sok., 16600 Gemlik / Bursa', 'phones'=>['0224 517 34 00','0224 517 34 08','0224 517 35 98'], 'source'=>$alo171],
    ['name'=>'Gürsu Sağlıklı Hayat Merkezi', 'district'=>'Gürsu', 'type'=>'Sağlıklı Hayat Merkezi', 'address'=>'İstiklal Mah. Atatürk Cad. No:85, 16580 Gürsu / Bursa', 'phones'=>['0224 371 00 50'], 'source'=>$alo171],
    ['name'=>'İnegöl Sağlıklı Hayat Merkezi', 'district'=>'İnegöl', 'type'=>'Sağlıklı Hayat Merkezi', 'address'=>'Kemalpaşa Mah. Dr. Ahmet Ufuk Tokcan Sok. No:4, İnegöl / Bursa', 'phones'=>['0224 715 17 27'], 'source'=>$alo171, 'contact_source'=>$shmContacts, 'note'=>'ALO 171 poliklinik telefonu yukarıdadır. Bakanlık SHM iletişim kaydındaki alternatif numara: 0224 713 11 77.', 'alternate_phone'=>'0224 713 11 77'],
    ['name'=>'Mudanya Sağlıklı Hayat Merkezi', 'district'=>'Mudanya', 'type'=>'Sağlıklı Hayat Merkezi', 'address'=>'Ömerbey Mah. Halitpaşa Cad. No:61 (Eski Hastane), 16940 Mudanya / Bursa', 'phones'=>['0224 544 53 43'], 'source'=>$alo171],
    ['name'=>'Mustafakemalpaşa Devlet Hastanesi', 'district'=>'Mustafakemalpaşa', 'type'=>'Hastane', 'address'=>'Tatkavaklı Mah. Kır Yolu Sok., 16550 Mustafakemalpaşa / Bursa', 'phones'=>['0224 613 18 60'], 'source'=>$alo171, 'contact_source'=>'https://alo191.saglik.gov.tr/TR-89292/bursa.html', 'note'=>'Hastanenin Tatkavaklı yerleşkesi gösteriliyor. ALO 171 listesinde eski Çırpan / Sağlık Sok. adresi bulunduğundan polikliniğin hizmet binasını mutlaka telefonla teyit edin.'],
    ['name'=>'Orhangazi Devlet Hastanesi', 'district'=>'Orhangazi', 'type'=>'Hastane', 'address'=>'Arapzade Mah. Tekneliküp Fındıklı Yolu Cad. No:65, 16800 Orhangazi / Bursa', 'phones'=>['0224 573 12 70'], 'source'=>$alo171, 'contact_source'=>'https://orhangazidh.saglik.gov.tr/TR-79500/bize-ulasin.html', 'note'=>'Kurum santrali yukarıdadır. Randevu seçenekleri için MHRS / ALO 182’yi kullanabilirsiniz.'],
    ['name'=>'Orhangazi Sağlıklı Hayat Merkezi', 'district'=>'Orhangazi', 'type'=>'Sağlıklı Hayat Merkezi', 'address'=>'Arapzade Mah. Erenler Cad. Hastane Sok. No:2, Orhangazi / Bursa', 'phones'=>['0224 573 34 68'], 'source'=>$alo171, 'contact_source'=>'https://bursaism.saglik.gov.tr/TR-15566/orhangazi-ilce-saglik-mudurlugu.html', 'note'=>'ALO 171 ve İl Sağlık Müdürlüğünün poliklinik adresi kullanıldı. Diğer Bakanlık listesinde Erenler Cad. No:91 (Eski Devlet Hastanesi) yazıyor; giriş bilgisini arayarak doğrulayın.'],
    ['name'=>'Yenişehir Sağlıklı Hayat Merkezi', 'district'=>'Yenişehir', 'type'=>'Sağlıklı Hayat Merkezi', 'address'=>'Kurtuluş Mah. Atatürk Cad. No:62, Yenişehir / Bursa', 'phones'=>['0224 772 24 99'], 'source'=>$alo171],
    ['name'=>'Büyükorhan İlçe Devlet Hastanesi', 'district'=>'Büyükorhan', 'type'=>'Hastane', 'address'=>'Dr. İbrahim Öktem Cad. Okul Sok. No:11, Büyükorhan / Bursa', 'phones'=>['0224 841 20 05'], 'extension'=>'195', 'source'=>$alo171, 'note'=>'Santrali aradıktan sonra 195 dahili numarasını isteyin.'],
];
