CREATE TABLE IF NOT EXISTS settings (
 name VARCHAR(40) NOT NULL PRIMARY KEY,
 value TEXT NOT NULL,
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS login_attempts (
 key_hash CHAR(64) NOT NULL PRIMARY KEY,
 attempts INT NOT NULL DEFAULT 0,
 locked_until BIGINT NOT NULL DEFAULT 0
) CHARACTER SET ascii;

CREATE TABLE IF NOT EXISTS audio_listens (
 audio_key CHAR(64) NOT NULL PRIMARY KEY,
 plays BIGINT NOT NULL DEFAULT 0,
 last_listened BIGINT NOT NULL DEFAULT 0
);
